spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis_practice?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: tla0413

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: practice.mybatis.domain
